### ISSUE TITLE
Edit icon on hover in Custom Shortcuts

### ISSUE THREAD

**Issue by devartstar** [CircuitVerse/cv-frontend-vue#54] opened 2023-01-07 12:43 UTC
**Describe the bug**
Hovering on custom shortcut must show an edit(`pencil`) icon.

**To Reproduce**
1. Go to Navbar -> Tools
2. Click on Custom Shortcut
3. Hover on any of them
4. Compare with [www.circuitverse.org](www.circuitverse.org)

**Screenshots**
<img width="719" alt="Screenshot 2023-01-07 at 5 32 51 PM" src="https://user-images.githubusercontent.com/61665451/211151183-2a13f7ab-cbcf-4319-8de6-c0d690005d05.png">

**Device Information [optional]:**

**Are you working on this issue? (Yes/No)**
No

**Comment by palashb01** [comment] 2023-01-07 13:26
Hey @devartstar , I would love to work on this, could you please assign this Issue to me, Thanks.

**Comment by Shu12388y** [comment] 2023-01-11 04:11
Hi, shubham here can you assign this issue to me.  I would love to work on this issue

**Comment by palashb01** [comment] 2023-01-11 06:05
Hello @Shu12388y , i have already raised a PR and it is under review you can checkout other issues,. Thanks.

**Comment by Krupalll20** [comment] 2023-03-06 06:10
heyyy @palashb01 is this issue still open to contribute?

**Comment by Adarsh9306** [comment] 2023-04-02 16:06
Heyy @devartstar if the issue is still open , can I work on this issue? please assign it to me.

**Comment by souravgope** [comment] 2023-11-25 03:18
i want to work on this issue please assgin me

**Closed** 2024-01-03 15:23 UTC
Labels: good first issue
