### ISSUE TITLE
Draggable components are overlapping with the navbar.

### ISSUE THREAD

**Issue by ArnabBCA** [CircuitVerse/cv-frontend-vue#195] opened 2023-11-21 08:47 UTC
**Describe the bug**
The draggable components are overlapping with the navbar

**To Reproduce**
1. Go to https://circuitverse.org/simulator
2. Drag the components

**Expected behavior**
The draggable components should be draggable only inside the canvas area.

**Screenshots**
![image](https://github.com/CircuitVerse/cv-frontend-vue/assets/113178195/31e7ee32-5b29-4cee-b681-8ca1eaefd3f3)

**Are you working on this issue? (Yes)**

**Comment by ArnabBCA** [comment] 2023-11-21 08:48
I would like to work on this issue.

**Comment by tanmoysrt** [comment] 2023-11-21 13:00
cc @Prerna-0202 @Arnabdaz

**Comment by ArnabBCA** [comment] 2023-11-21 13:03
> cc @Prerna-0202 @Arnabdaz 

May I know what you are doing?

**Comment by tanmoysrt** [comment] 2023-11-21 13:04
> > cc @Prerna-0202 @Arnabdaz
> 
> May I know what you are doing?

They can verify the issue and assign you !

**Comment by Prerna-0202** [comment] 2023-11-22 18:55
Hey @ArnabBCA, Thank you for opening an issue.
I am just curious to know. Is it a suggestion, or do you believe it is a bug? If you consider it a bug, I would like to understand how it could be beneficial.

**Comment by ArnabBCA** [comment] 2023-11-22 19:00
> Hey @ArnabBCA, Thank you for opening an issue.
> I am just curious to know. Is it a suggestion, or do you believe it is a bug? If you consider it a bug, I would like to understand how it could be beneficial.
> 
> 
> 
> 
> 
> 
> 

I think it is a bug because the draggable components should only be draggable inside the Canvas area. Currently it is restricted inside the whole body. As a result it is not considering the navbar and tabs bar height.

**Comment by ArnabBCA** [comment] 2023-11-22 19:04
> > Hey @ArnabBCA, Thank you for opening an issue.
> > I am just curious to know. Is it a suggestion, or do you believe it is a bug? If you consider it a bug, I would like to understand how it could be beneficial.
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> 
> I think it is a bug because the draggable components should only be draggable inside the Canvas area. Currently it is restricted inside the whole body. As a result it is not considering the navbar and tabs bar height. 

If it is overlapping the navbar the user cannot do any navbar actions. He/she  has to drag again inside the Canvas in order to use the navbar actions

**Comment by ArnabBCA** [comment] 2023-11-23 18:21
@Prerna-0202 can I proceed?

**Comment by Prerna-0202** [comment] 2023-11-23 18:35
I understand your perspective, but the current setup aligns with the expected behavior. You can check out other open issues.

**Comment by nickhil-verma** [comment] 2023-11-28 17:25
Is this issue Open and should i work on it ??

**Comment by Arnabdaz** [comment] 2023-12-22 16:46
This issue is closed as it is the intended behavior.

**Closed** 2024-01-03 14:45 UTC
